$wallpaper=~/nix/wallpaper/blossom.png

$active=rgb(E283BA)
$inactive=rgb(000000)

$borderSize=3
$gaps=10
$rounding=10
$floatingRounding=$rounding

$indicatorHeight=4
$indicatorRounding={{indicatorHeight / 2}}
