$wallpaper=~/nix/wallpaper/house.jpg

$active=rgb(47735F)
# $active=rgb(fce99f)
# $active=rgb(8ec07c)
# $active=rgb(ce8d25)
$inactive=rgb(000000)

$borderSize=0
$gaps=8
$rounding=10
$floatingRounding=$rounding

$indicatorHeight=4
$indicatorRounding={{indicatorHeight / 2}}
