#!/usr/bin/env bash

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$MY_ENV" ]; then
    MY_ENV="$HOME/env"
fi

if [ -z "$MY_CONFIG" ]; then
    MY_CONFIG="$MY_ENV/environment/config"
fi

if [ -z "$MY_OVERLAYS" ]; then
    MY_OVERLAYS="$MY_ENV/environment/overlays"
fi

if [ -z "$HOST" ]; then
    HOST=$(hostname)
fi

if [ -z "$OVERLAY" ]; then
    if [ -f "$MY_OVERLAYS/$HOST" ]; then
        OVERLAY=$(<"$MY_OVERLAYS/$HOST")
    else
        OVERLAY=$(<"$MY_OVERLAYS/current")
    fi
fi

move () {
    dir="$1"
    to="$2"
    if [ -d "$to" ] && [ -d "$dir" ]; then
        rm -rf "$to"
        cp -R "$dir" "$to"
        return 0
    fi
    if [ -f "$to" ] && [ -f "$dir" ]; then
        rm -f "$to"
        cp "$dir" "$to"
    fi
}

overlay=""
config=""

for arg in "$@"; do
    if [[ "$arg" == "--overlay" ]]; then
        overlay=1
    else
        config="$arg"
    fi
done

if [ -n "$overlay" ]; then
    to="$MY_OVERLAYS/$OVERLAY/$config"
else
    to="$MY_CONFIG/$config"
fi

from="$XDG_CONFIG_HOME/$config"
move "$from" "$to"
