#!/usr/bin/env bash

configuration="$1"

if [ -z "$configuration" ]; then
    echo "Usage: $0 <configuration>"
    exit 1
fi

sudo nix --extra-experimental-features 'nix-command flakes' build --no-sandbox --print-out-paths ".#nixosConfigurations.\"$configuration\".config.system.build.toplevel" --no-link
