#!/usr/bin/env bash

configuration="$1"

sudo nix --extra-experimental-features 'nix-command flakes' build --no-sandbox --print-out-paths ".#nixosConfigurations.\"$configuration\".config.system.build.toplevel" --no-link
