#!/usr/bin/env bash

searches=(
    "$HOME/work" "$HOME/dev"
)

extras=(
    "$HOME" "$HOME/nix"
)

extras=$(echo "${extras[@]}" | tr ' ' '\n')

options=$(find "${searches[@]}" -maxdepth 1 -mindepth 1 -type d ! -path "*/.*" 2> /dev/null)
options=$(echo -e "$extras\n$options")

selection=$(echo "$options" | fzf)
if [ -z "$selection" ]; then
    exit 1
fi

session "$selection"
