#!/usr/bin/env bash

if [ -z "$SELECTOR" ]; then
    SELECTOR="fzf"
fi

case "$SELECTOR" in
    vicinae)
        vicinae dmenu -s "Options ({count})" -p "$1"
        ;;
    fuzzel)
        fuzzel --dmenu --placeholder="$1"
        ;;
    fzf)
        fzf
        ;;
    *)
        echo "Unknown selector: $SELECTOR"
        exit 1
        ;;
esac
