#!/usr/bin/env bash

if [ -z "$MY_ENV" ]; then
    MY_ENV="$HOME/env"
fi

if [ -z "$MY_OVERLAYS" ]; then
    MY_OVERLAYS="$MY_ENV/environment/overlays"
fi

overlay_names="$(find "$MY_OVERLAYS" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)"

overlay="$(echo "$overlay_names" | head -c -1 | selector "Select overlay...")"

if [ -z "$overlay" ]; then
    echo "No overlay selected"
    exit 1
fi

OVERLAY="$overlay" switch-env
