#!/usr/bin/env bash

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$SESSIONS_HOME" ]; then
    SESSIONS_HOME="$XDG_CONFIG_HOME/sessions"
fi

if [ -z "$1" ]; then
    dir=$(pwd)
else
    dir="$1"
fi

if [ -d "$dir" ]; then
    name=$(basename "$dir")
else
    name="$dir"
    dir=$(pwd)
fi

open () {
    if [ -n "$TMUX" ]; then
        tmux switch -t "$1" &> /dev/null
    else
        tmux attach -t "$1" &> /dev/null
    fi
}

pushd "$dir" > /dev/null
(git fetch &> /dev/null)&
popd > /dev/null

if tmux has-session -t "$name" &> /dev/null ; then
    open "$name"
    exit 0
fi

tmux new-session -c "$dir" -s "$name" -d

if [ -f "$dir/.session" ]; then
    tmux send-keys -t "$name" "$dir/.session $name" c-M
elif [ -f "$SESSIONS_HOME/$name" ]; then
    tmux send-keys -t "$name" "$SESSIONS_HOME/$name $name" c-M
else
    tmux send-keys -t "$name" "default-session $name" c-M
fi

open "$name"
