#!/usr/bin/env bash

mode="dark"

while getopts "w:m:" opt; do
    case "$opt" in
        w)
            wallpaper="$OPTARG"
            ;;
        m)
            mode="$OPTARG"
            if [ "$mode" != "dark" ] && [ "$mode" != "light" ]; then
                echo "Invalid mode: $mode"
                exit 1
            fi
            ;;
        *)
            echo "Usage: $0 [-w <wallpaper>] [-m <mode>]"
            exit 1
            ;;
    esac
done

if [ -z "$wallpaper" ]; then
    if [ -z "$MY_NIX" ]; then
        MY_NIX="$HOME/nix"
    fi

    if [ -z "$XDG_CONFIG_HOME" ]; then
        XDG_CONFIG_HOME="$HOME/.config"
    fi

    if [ -z "$MY_WALLPAPERS" ]; then
        MY_WALLPAPERS="$MY_NIX/wallpaper"
    fi

    wallpaper="$MY_WALLPAPERS/$(<"$XDG_CONFIG_HOME/wallpaper/config")"
fi

noctalia_running=$(command -v noctalia-shell > /dev/null && noctalia-shell list | grep "Process ID" | awk '/Process ID: [0-9]+/ {print $3}')

if [ -f "$wallpaper" ]; then
    if [ -n "$noctalia_running" ]; then
        noctalia-shell ipc call wallpaper set "$wallpaper" all
    fi
    if command -v matugen &> /dev/null; then
        matugen image "$wallpaper" -t "scheme-tonal-spot" -m "$mode" --source-color-index 0 &> /dev/null
    fi
fi
