#!/usr/bin/env bash

if [ -z "$MY_NIX" ]; then
    MY_NIX="$HOME/nix"
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$MY_CONFIG" ]; then
    MY_CONFIG="$MY_NIX/environment/config"
fi

if [ -z "$SCRIPTS_HOME" ]; then
    SCRIPTS_HOME="$HOME/.local/scripts"
fi

if [ -z "$MY_SCRIPTS" ]; then
    MY_SCRIPTS="$MY_NIX/environment/scripts"
fi

if [ -z "$MY_HOSTS" ]; then
    MY_HOSTS="$MY_NIX/environment/hosts"
fi

if [ -z "$HOST" ]; then
    HOST=$(hostname)
fi

if [ -z "$MY_OVERLAYS" ]; then
    MY_OVERLAYS="$MY_NIX/environment/overlays"
fi

if [ -z "$OVERLAY" ]; then
    if [ -f "$MY_OVERLAYS/$HOST" ]; then
        OVERLAY=$(<"$MY_OVERLAYS/$HOST")
    else
        OVERLAY=$(<"$MY_OVERLAYS/current")
    fi
fi

if [ -z "$MY_WALLPAPERS" ]; then
    MY_WALLPAPERS="$MY_NIX/wallpaper"
fi

move () {
    dir="$1"
    to="$2"
    rm -rf "$to"
    cp -R "$dir" "$to"
}

apply-overlay () {
    selection="$1"
    if [ ! -d "$selection" ]; then
        return 0
    fi
    for file in $(find "$selection" -type f);
    do
        after=${file#"$selection/"}
        base=$(basename "$file")
        if [[ $base == "extension."* ]]; then
            newfile="$XDG_CONFIG_HOME/${after%"$base"}${base#"extension."}"
            cat "$file" >> "$newfile"
        else
            newfile="$XDG_CONFIG_HOME/$after"
            cp "$file" "$newfile"
        fi
    done
}

vicinae_running=$(pgrep vicinae)
ghostty_running=$(pgrep ghostty)
noctalia_running=$(command -v noctalia-shell > /dev/null && noctalia-shell list | grep "Process ID" | awk '/Process ID: [0-9]+/ {print $3}')

if [ -n "$vicinae_running" ]; then
    pkill vicinae
fi

if [ -n "$noctalia_running" ]; then
    kill -STOP "$noctalia_running"
fi

move "$MY_SCRIPTS" "$SCRIPTS_HOME"
chmod -R +x "$SCRIPTS_HOME"

for config in $(find "$MY_CONFIG" -maxdepth 1 -mindepth 1 -type d);
do
    base=$(basename $config)
    move "$config" "$XDG_CONFIG_HOME/$base"
done

chmod -R +x "$XDG_CONFIG_HOME/sessions"

cp "$MY_CONFIG/zshrc" "$HOME/.zshrc"
cp "$MY_CONFIG/bashrc" "$HOME/.bashrc"

apply-overlay "$MY_HOSTS/$HOST"
apply-overlay "$MY_OVERLAYS/$OVERLAY"

if [ -n "$vicinae_running" ]; then
    vicinae server &> /dev/null &
fi

if [ -n "$ghostty_running" ]; then
    systemctl reload --user app-com.mitchellh.ghostty.service
fi

if [ -n "$noctalia_running" ]; then
    kill -CONT "$noctalia_running"
    wallpaper="$MY_WALLPAPERS/$(<"$XDG_CONFIG_HOME/wallpaper/config")"
    if [ -f "$wallpaper" ]; then
        #if command -v matugen > /dev/null && command -v jq > /dev/null; then
        #    matugen_config="$HOME/.cache/noctalia/theming.dynamic.toml"
        #    noctalia_config="$XDG_CONFIG_HOME/noctalia/settings.json"
        #    if [ -f "$matugen_config" ] && [ -f "$noctalia_config" ]; then
        #        run_matugen="$(cat "$noctalia_config" | jq 'if .colorSchemes.useWallpaperColors then "true" else "" end' -r)"
        #        if [ -n "$run_matugen" ]; then
        #            matugen_type="$(cat "$noctalia_config" | jq '.colorSchemes.generationMethod' -r)"
        #            matugen_mode="$(cat "$noctalia_config" | jq 'if .colorSchemes.darkMode then "dark" else "light" end' -r)"
        #            if [ -n "$matugen_type" ] && [ -n "$matugen_mode" ]; then
        #            #if [ -n "$matugen_mode" ]; then
        #                matugen image "$wallpaper" -c "$matugen_config" -t "scheme-$matugen_type" -m "$matugen_mode"
        #                #matugen image "$wallpaper" -c "$matugen_config" -m "$matugen_mode" &> /dev/null
        #            fi
        #        else
        #            color_scheme="$(cat "$noctalia_config" | jq '.colorSchemes.predefinedScheme' -r)"
        #            if [ -n "$color_scheme" ]; then
        #                noctalia-shell ipc call colorScheme set "$color_scheme" &> /dev/null
        #            fi
        #        fi
        #    fi
        #fi
        noctalia-shell ipc call wallpaper set "$wallpaper" "all" &> /dev/null
    fi
fi

if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
    hyprctl reload
fi
