#!/usr/bin/env bash

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$MY_CONFIG" ]; then
    MY_CONFIG="$HOME/nix/environment/config"
fi

if [ -z "$SCRIPTS_HOME" ]; then
    SCRIPTS_HOME="$HOME/.local/scripts"
fi

if [ -z "$MY_SCRIPTS" ]; then
    MY_SCRIPTS="$HOME/nix/environment/scripts"
fi

if [ -z "$SESSIONS_HOME" ]; then
    SESSIONS_HOME="$HOME/.local/sessions"
fi

if [ -z "$MY_SESSIONS" ]; then
    MY_SESSIONS="$HOME/nix/environment/sessions"
fi

if [ -z "$MY_HOSTS" ]; then
    MY_HOSTS="$HOME/nix/environment/hosts"
fi

if [ -z "$HOST" ]; then
    HOST=$(hostname)
fi

if [ -z "$MY_OVERLAYS" ]; then
    MY_OVERLAYS="$HOME/nix/environment/overlays"
fi

if [ -z "$OVERLAY" ]; then
    OVERLAY=$(<"$MY_OVERLAYS/current")
fi

move () {
    dir="$1"
    to="$2"
    rm -rf "$to"
    cp -R "$dir" "$to"
}

apply-overlay () {
    selection="$1"
    for file in $(find "$selection" -type f);
    do
        after=${file#"$selection/"}
        base=$(basename "$file")
        if [[ $base == "extension."* ]]; then
            newfile="$XDG_CONFIG_HOME/${after%"$base"}${base#"extension."}"
            cat "$file" >> "$newfile"
        else
            newfile="$XDG_CONFIG_HOME/$after"
            cp "$file" "$newfile"
        fi
    done
}

move "$MY_SCRIPTS" "$SCRIPTS_HOME"
chmod -R +x "$SCRIPTS_HOME"

move "$MY_SESSIONS" "$SESSIONS_HOME"
chmod -R +x "$SESSIONS_HOME"

for config in $(find "$MY_CONFIG" -maxdepth 1 -mindepth 1 -type d);
do
    base=$(basename $config)
    move "$config" "$XDG_CONFIG_HOME/$base"
done

cp "$MY_CONFIG/zshrc" "$HOME/.zshrc"

apply-overlay "$MY_HOSTS/$HOST"
apply-overlay "$MY_OVERLAYS/$OVERLAY"

if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
    pkill waybar
    waybar &> /dev/null &
    hyprctl reload
fi
