#!/usr/bin/env bash

command="$1"

if [ -z "$command" ] || ! { [ "$command" = "toggle-pin" ] || [ "$command" = "toggle-display" ] || [ "$command" = "toggle-orientation" ] || [ "$command" = "sync" ] || [ "$command" = "resize" ] || [ "$command" = "test" ]; }; then
    echo "Usage: $(basename "$0") <toggle-pin|toggle-display|toggle-orientation|sync|resize|test> [sync target]"
    exit 1
fi

if [ -z "$XDG_STATE_HOME" ]; then
    XDG_STATE_HOME="$HOME/.local/state"
fi

get_pane_width() {
    pane_id="$1"
    w_width=$(tmux display-message -t "$pane_id" -p "#{window_width}")
    p_width=$(tmux display-message -t "$pane_id" -p "#{pane_width}")
    echo "$(( (p_width * 100) / w_width ))%"
}

get_pane_height() {
    pane_id="$1"
    w_height=$(tmux display-message -t "$pane_id" -p "#{window_height}")
    p_height=$(tmux display-message -t "$pane_id" -p "#{pane_height}")
    echo "$(( (p_height * 100) / w_height ))%"
}

session=$(tmux display-message -p "#{session_name}")
pane_id=$(tmux display-message -p "#{pane_id}")
window_id=$(tmux display-message -p "#{window_id}")

if [ -z "$pane_id" ] || [ -z "$session" ] || [ -z "$window_id" ]; then
    exit 1
fi

session_file="$XDG_STATE_HOME/tmux-pin-pane/$session"

if ! [ -d "$XDG_STATE_HOME/tmux-pin-pane" ]; then
    mkdir -p "$XDG_STATE_HOME/tmux-pin-pane"
fi

if [ "$command" = "toggle-pin" ]; then
    if [ -f "$session_file" ]; then
        read -r pin_pane < "$session_file"
        if [ "$pane_id" = "$pin_pane" ]; then
            rm "$session_file"
            exit 0
        fi
    fi
    tmux join-pane -v -s "$pane_id" -t "$window_id.{bottom}"
    sleep 0.5
    size=$(get_pane_height "$pane_id")
    if [ "$size" = "100%" ]; then
        size="30%"
    fi
    echo -e "$pane_id\n$size\nshow\nvertical" > "$session_file"
elif [ "$command" = "sync" ]; then
    if ! [ -f "$session_file" ]; then
        exit 0
    fi
    {
        read -r pin_pane
        read -r size
        read -r display
        read -r orientation
    } < "$session_file"
    if ! tmux has-session -t "$pin_pane"; then
        rm "$session_file"
        exit 0
    fi
    detach="-d"
    if [ "$display" = "show" ]; then
        target="$2"
        if [ -z "$target" ]; then
            if [ "$orientation" = "vertical" ]; then
                target="$window_id.{bottom}"
            else
                target="$window_id.{left}"
            fi
        fi
        if tmux has-session -t ":98"; then
            tmux kill-pane -t ":98"
            detach=""
        fi
    else
        if ! tmux has-session -t ":98"; then
            tmux neww -t ":98" -d
        fi
        target=":98"
    fi
    split="-v"
    if [ "$orientation" = "horizontal" ]; then
        split="-hb"
    fi
    target_pane_id=$(tmux display-message -t "$target" -p "#{pane_id}")
    if [ "$target_pane_id" = "$pin_pane" ]; then
        exit 0
    fi
    tmux join-pane $detach $split -s "$pin_pane" -t "$target" -l "$size"
elif [ "$command" = "resize" ]; then
    if ! [ -f "$session_file" ]; then
        exit 0
    fi
    {
        read -r pin_pane
        read -r _
        read -r display
        read -r orientation
    } < "$session_file"
    if ! tmux has-session -t "$pin_pane"; then
        rm "$session_file"
        exit 0
    fi
    sleep 0.5
    if [ "$orientation" = "vertical" ]; then
        size="$(get_pane_height "$pin_pane")"
    else
        size="$(get_pane_width "$pin_pane")"
    fi
    if [ "$size" = "100%" ]; then
        size="30%"
    fi
    echo -e "$pin_pane\n$size\n$display\n$orientation" > "$session_file"
elif [ "$command" = "toggle-display" ]; then
    if ! [ -f "$session_file" ]; then
        tmux split-window -v -t "$window_id.{bottom}" -l "30%"
        "$0" toggle-pin
        exit 0
    fi
    {
        read -r pin_pane
        read -r size
        read -r display
        read -r orientation
    } < "$session_file"
    if [ "$display" = "show" ]; then
        display="hide"
    else
        display="show"
    fi
    echo -e "$pin_pane\n$size\n$display\n$orientation" > "$session_file"
    "$0" sync
elif [ "$command" = "toggle-orientation" ]; then
    if ! [ -f "$session_file" ]; then
        exit 0
    fi
    {
        read -r pin_pane
        read -r size
        read -r display
        read -r orientation
    } < "$session_file"
    if [ "$orientation" = "vertical" ]; then
        orientation="horizontal"
    else
        orientation="vertical"
    fi
    echo -e "$pin_pane\n$size\n$display\n$orientation" > "$session_file"
    "$0" sync
elif [ "$command" = "test" ]; then
    if [ -z "$TMUX" ] || [ ! -f "$session_file" ]; then
        exit 1
    fi
    read -r pin_pane < "$session_file"
    [ "$pin_pane" = "$pane_id" ]
fi
