#!/usr/bin/env bash

gen () {
    if gen-trade "$1" "$2"; then
        mdp trade.md --fade
    fi
}

while true; do
    gen "$1" "$2" &
    PID=$!
    inotifywait -e modify -e move -e create -e delete -e attrib "$1.md" "$2.md"
    kill $PID
done
