#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $(basename "$0") <MAC-ADDRESS>"
    exit 1
fi

mac="$1"
mac="${mac//[:.-]/}"

if [ -z "$BROADCAST_ADDRESS" ]; then
    BROADCAST_ADDRESS="255.255.255.255"
fi

payload=""
for _ in {1..6}; do
    payload+="ff"
done
for _ in {1..16}; do
    payload+="$mac"
done
payload=$(echo -n "$payload" | xxd -r -p)

echo -n "$payload" | socat - UDP4-DATAGRAM:"$BROADCAST_ADDRESS":9,broadcast
