#!/usr/bin/env bash

if [ -z "$HOST" ]; then
    HOST=$(hostname)
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$MY_CONFIG" ]; then
    MY_CONFIG="$HOME/nix/homeManager/config"
fi

if [ -z "$MY_HOST_CONFIG" ]; then
    MY_HOST_CONFIG="$HOME/nix/homeManager/hostConfig/$HOST"
fi

if [ -z "$SCRIPTS_HOME" ]; then
    SCRIPTS_HOME="$HOME/.local/scripts"
fi

if [ -z "$MY_SCRIPTS" ]; then
    MY_SCRIPTS="$HOME/nix/homeManager/scripts"
fi

if [ -z "$SESSIONS_HOME" ]; then
    SESSIONS_HOME="$HOME/.local/sessions"
fi

if [ -z "$MY_SESSIONS" ]; then
    MY_SESSIONS="$HOME/nix/homeManager/sessions"
fi

move () {
    dir="$1"
    to="$2"
    rm -rf "$to"
    cp -R "$dir" "$to"
}

append_host_to_config () {
    config="$XDG_CONFIG_HOME/$1"
    host="$MY_HOST_CONFIG/$1"
    if ! [ -f "$config" ]; then
        exit 0
    fi
    if ! [ -f "$host" ]; then
        exit 0
    fi
    cat "$host" >> "$config"
}

move "$MY_SCRIPTS" "$SCRIPTS_HOME"
chmod -R +x "$SCRIPTS_HOME"

move "$MY_SESSIONS" "$SESSIONS_HOME"
chmod -R +x "$SESSIONS_HOME"

for config in $(find "$MY_CONFIG" -maxdepth 1 -mindepth 1 -type d);
do
    base=$(basename $config)
    if [ "$base" = "hypr" ]; then
        continue
    fi
    move "$config" "$XDG_CONFIG_HOME/$base"
done

pkill waybar
waybar &

if [ "$1" = "--hypr" ]; then
    move "$MY_CONFIG/hypr" "$XDG_CONFIG_HOME/hypr"
    append_host_to_config "hypr/hyprland.conf"
    hyprctl reload
fi
