#!/usr/bin/env bash

session=$(tmux display-message -p "#{session_name}")
app="$1"
window="$session:$2"

if ! tmux select-window -t "$window" &> /dev/null; then
    tmux neww -t "$window" -d
    tmux send-keys -t "$window" "$app" c-M
    tmux select-window -t "$window"
fi
