$wallpaper=~/nix/wallpaper/house.jpg

$active=rgb(47735F)
$inactive=rgb(000000)

$borderSize=0
$gaps=10
$rounding=10
$floatingRounding=$rounding

$indicatorHeight=4
$indicatorRounding={{indicatorHeight / 2}}
